#!/usr/bin/env bash
# battery.sh — Launch the battery tray monitor
# Generated by install.sh — do not edit the path below manually; re-run install.sh

sleep 5   # wait for the desktop environment to fully start
cd "$(dirname "$(readlink -f "$0")")"
DISPLAY=':0.0' python3 batteryTray.py
